apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-deploy
spec:
  selector:
    matchLabels:
      color: red
  template:
    metadata:
      labels:
        color: red
    spec:
      containers:
      - name: red-ctn
        image: chlwhdals264/keduitlab:red
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: red-lb
spec:
  type: LoadBalancer
  selector:
    color: red
  ports:
  - port: 80
    targetPort: 80